# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#accent-color
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#details
# mkdocs.yml
site_name: WRF-ARW installation on AWS using SPACK

# Copyright
copyright: Copyright &copy; 2022 <a href="http://atmosfera.usm.my/" target="_blank">atmosfera.usm.my</a>

# Configuration
theme:
  name: material
  features:
    #- announce.dismiss
    #- content.code.annotate
    - content.tabs.link
    #- content.tooltips
    #- header.autohide
    #- navigation.expand
    #- navigation.indexes
    #- navigation.instant
    #- navigation.prune
    #- navigation.sections
    #- navigation.tabs
    - navigation.tabs.sticky
    #- navigation.top
    #- navigation.tracking
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.follow
    #- toc.integrate

  palette:
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

# Extensions
markdown_extensions:
  - pymdownx.critic
  - attr_list
  # Note
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  # Code Block
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Tabs
  - pymdownx.tabbed:
      alternate_style: true 
  # Table
  - tables

plugins:
  - mkdocstrings
  - autorefs
  - search
nav:
  - Overview: index.md
  - Website: web.md